name: pipeline

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      users: actions/checkout@v2

    - name: Npm install
      run: npm install

    - name: Npm build
      run: npm run build

    - name: List Directory
      run: ls -la build